### ISSUE TITLE
[Design] 밈 생성 UI 구현

### ISSUE THREAD

**Issue by youngseo3** [tukcomCD2024/SnowBall#13]
## Description
- 밈 생성 UI 구현 및 화면전환

## To-Do
- [x] 바텀네비게이션 뷰 개발
- [x] 템플릿 UI 개발
- [x] 얼굴 사진 선택 UI 개발
- [x] 목소리 선택 UI 개발
- [x] 대사 입력 UI 개발
- [x] 결과 미리보기 UI 개발
