### ISSUE TITLE
[Feat] 목소리 선택 구현

### ISSUE THREAD

**Issue by youngseo3** [tukcomCD2024/SnowBall#25]
## Description
- 밈 생성 UI에서 사용자는 밈 생성을 위해 하나의 씬에 목소리를 선택할 수 있다.

## To-Do
- [x] 목소리 파일(예제) 안드로이드 앱에 넣기
- [ ] 플레이 버튼 누르면 음성이 들리도록 하기
- [x] 선택이 되면 SceneDetailFragment에 나오도록
