### ISSUE TITLE
[Chore] server-cicd 연동하기

### ISSUE THREAD

**Issue by JunRain2** [tukcomCD2024/SnowBall#38]
## Description
WAS 서버에 대해 깃허브 액션을 통해 CI-CD 구현하기

## To-Do
- [x] docekr-compose 파일 작성하기
- [x] github-action 파일 작성하기
- [x] gradlew jib의 실행 방식 생각해보기
    - [x] github action에서 설정파일을 어떻게 할 것인지 생각하기

## ETC
여력이 된다면 깃허브 액션이 아닌 jenkins 사용해 보기
