### ISSUE TITLE
[Feat] WAS 서버 밈 생성 및 밈 조회 구현

### ISSUE THREAD

**Issue by JunRain2** [tukcomCD2024/SnowBall#42]
## Description
- 밈 생성을 위해 AI 서버 연결
- 밈 전체 조회 구현
- 밈 상세 조회 구현

## To-Do
- [x] 밈 생성을 위한 AI 서버 연결
- [x] 밈 전체 조회 구현
- [x] 밈 상세 조회 구현
