### ISSUE TITLE
[Chore] AI서버 CI-CD 구축하기

### ISSUE THREAD

**Issue by JunRain2** [tukcomCD2024/SnowBall#46]
## Description
- memetory-ai 작성해서 서버에 올리기

## To-Do
- [x] dockerfile 다시 작성하기
- [ ] github actions 작성하기
- [x] #54
    - [x]  config 파일 분리
    - [x]  config 분리로 인한 클래스들 리팩토링
    - [x]  `Module` 형식의 `.py` 파일을 `Class` 형식으로 리팩토링
    - [x]  밈을 생성하는 일련의 과정을 메서드로 분리
         - 차후 celery로 실행하기 위함
