### ISSUE TITLE
[Design] 온보딩 UI 구현

### ISSUE THREAD

**Issue by youngseo3** [tukcomCD2024/SnowBall#6]
## Description
- 스플래쉬, 로그인, 앱을 어떻게 사용하는 가에 대한 방법을 제시하는 가이드 UI 구현

## To-Do
- [x] 기본적인 로고나 이미지 에셋, 폰트 추가하기
- [x] 스플래쉬 UI 구현
- [x] 로그인 UI 구현
- [x] 가이드 UI 구현
