### ISSUE TITLE
[Design] 온보딩 UI 구현

### ISSUE THREAD

**Issue by SeungEEE** [tukcomCD2024/SnowBall#7]
## Description
- 앱을 처음 실행시킬 때 나오는 런치스크림 UI, 앱 사용 설명 가이드 UI, 로그인 UI 구현

## To-Do
- [x] 런치스크린 UI 구현
- [x] 가이드 UI 구현
- [x] 로그인 UI 구현

**Comment by SeungEEE** [comment]
good
