### ISSUE TITLE
[Feat] Redis를 통한 리더보드 구현

### ISSUE THREAD

**Issue by JunRain2** [tukcomCD2024/SnowBall#92]
## Description
- Redis의 sorted set을 활용하여 리더보드를 구현
- 책 "개발자를 위한 레디스"의 내용을 참조하여 구현

## To-Do
- [x] Redis 환경 세팅
    - [x] Redis template 설정
- [x] RedisService 구현
  - [x] Score 증가 구현
  - [x] Score 감소 구현
  - [x] 조회 구현
      - [x] 주간 랭킹
      - [x] 월간 랭킹
