### ISSUE TITLE
[Feat] FCM 및 밈 전체조회 구현

### ISSUE THREAD

**Issue by youngseo3** [tukcomCD2024/SnowBall#96]
## Description
- FCM, 보관함에 밈 조회

## To-Do
- [x] 미리보기 화면 삭제, 로딩창 삭제
- [x] ChooseTemplate 화면 -> 홈으로 이동
- [x] FCM 구현
- [x] 보관함으로 들어가면 밈 전체조회 api 호출
